server:
  port: 8080
spring:
  application:
    name: deforestation-back
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/deforestation?useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false